include:
  - board: nice_nano_v2//zmk  # Use nice_nano//zmk if you specifically have the older v1 controller
    shield: cradio_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2//zmk
    shield: cradio_right
