include:
  - board: nrfmicro@1.1/nrf52840/zmk
    shield: cradio_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nrfmicro@1.1/nrf52840/zmk
    shield: cradio_right
